[project]
name = "fastapiproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "loguru>=0.7.3",
    "mysql-connector-python>=9.5.0",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
